[package]
name = "caribon-server"
version = "0.7.0"
authors = ["Elisabeth Henry <liz.henry@ouvaton.org>"]

[dependencies]
iron = "0.2.6"
caribon = "0.7"
router = "0.1"
urlencoded = "0.2"
hyper = "0.7"